sudo: required
services: 
  - docker

before_install:
  - docker build -t rht6226/react-frontend -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true rht6226/react-frontend npm test

after_success:
  - docker build -t rht6226/complex-app-client ./frontend
  - docker build -t rht6226/complex-app-nginx ./nginx
  - docker build -t rht6226/complex-app-server ./server
  - docker build -t rht6226/complex-app-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rht6226/complex-app-client
  - docker push rht6226/complex-app-nginx
  - docker push rht6226/complex-app-server
  - docker push rht6226/complex-app-worker

